version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      - spring-network

  wantedpreonboardingbackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql-data:
