spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${custom.prod.db.url}'
    username: '${custom.prod.db.username}'
    password: '${custom.prod.db.password}'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 1000
logging:
  level:
    root: INFO
    wantedpreonboardingbackend: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
custom:
  site:
    baseUrl: '${custom.prod.site.url}'